export type ComponentTypes =
    | "text"
    | "title"
    | "citation"
    | "code"
    | "separator"
    | "geometric"
    | "image"
    | "sheet"
    | "code"
    | "math"
    | "lineChart"
    | "barChart"
    | "sectorChart"
    | "line"
    | "columns"
    | "non-uniform-columns";
